### ISSUE TITLE
this.$refs.myAccordian.open(0) doesnt seem to work

### ISSUE THREAD

**Issue by darthShana** [vanderb/vue-badger-accordion#3]
Hi 
this is probably because im not using it correctly..
but on mount
im calling 
this.$refs.myAccordian.open(0)
but that doesnt seem to do anything.. And all panels are closed

however
this.$refs.myAccordian.openAll()
does work and opens all panels

**Comment by Grawl** [comment]
`this.$refs.orderStatusAccordion.accordion.open(val)` works

**Comment by vanderb** [comment]
Thanks for report that issue.
The index-parameter was missing in the main component, so it does not pass it to badger itself.
So, thats the reason the example of @Grawl works (because he accessing the original Badger-Instance via .accordion.open(index)

Sorry, fixed that in v. 1.0.9. 

Now your code should work like expected

Btw.. You also can pass now an array of indexes (like in the documentation).

Let me know if there are other bugs, thank you.
